export default {

    bg : require('../assests/images/appLogo/bg.png'),
    logo : require('../assests/images/appLogo/logo.png'),
    facebook : require('../assests/images/social/facebook.png'),
    google : require('../assests/images/social/google.png'),
    twitter : require('../assests/images/social/twitter.png'),
    email : require('../assests/images/smallIcons/email.png'),
    lock : require('../assests/images/smallIcons/lock.png'),
    user : require('../assests/images/smallIcons/user.png'),
    email : require('../assests/images/smallIcons/email.png'),
    shape : require('../assests/images/smallIcons/shape.png'),
    gender : require('../assests/images/smallIcons/gender.png'),
    arrow : require('../assests/images/smallIcons/arrow.png'),
    weightScale : require('../assests/images/smallIcons/weightScale.png'),
    arctic : require('../assests/images/smallIcons/arctic.png'),
    height : require('../assests/images/smallIcons/heightRuker.png'),
    lotus : require('../assests/images/lotus/lotus2.png'),
    bitmap : require('../assests/images/walkthroughImages/bitmap.png'),
    bitmap1 : require('../assests/images/walkthroughImages/bitmap1.png'),
    right : require('../assests/images/smallIcons/shape1.png'),
    group11 : require('../assests/images/walkthroughImages/group11.png'),
    breathing : require('../assests/images/bottomIcons/breathing.png'),
    experience : require('../assests/images/bottomIcons/experience.png'),
    parameters : require('../assests/images/bottomIcons/parameters.png'),
    daily : require('../assests/images/bottomIcons/daily.png'),

}